# Generated by Django 2.1.2 on 2018-10-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
    ]
